version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ef-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
