// <auto-generated />
using System;
using BuildCv.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildCv.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BuildCvDbContext))]
    [Migration("20260805124022_AddReadabilityReports")]
    partial class AddReadabilityReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildCv.Domain.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)")
                        .HasColumnName("Email")
                        .HasAnnotation("BuildCv:Encrypted", true)
                        .HasAnnotation("BuildCv:EncryptionContext", "Account.Email");

                    b.Property<byte[]>("EmailHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasAnnotation("BuildCv:BlindIndexFor", "Account.Email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.ToTable("Accounts", "identity");
                });

            modelBuilder.Entity("BuildCv.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<byte[]>("Token")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)")
                        .HasColumnName("Token")
                        .HasAnnotation("BuildCv:Encrypted", true)
                        .HasAnnotation("BuildCv:EncryptionContext", "RefreshToken.Token");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasAnnotation("BuildCv:BlindIndexFor", "RefreshToken.Token");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("BuildCv.Domain.Jobs.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset?>("ClosesAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("EducationLevel")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("Status");

                    b.HasIndex("CompanyId", "Seq");

                    b.HasIndex("OwnerId", "Seq");

                    b.ToTable("JobPostings", "jobs");
                });

            modelBuilder.Entity("BuildCv.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("Organizations", "orgs");
                });

            modelBuilder.Entity("BuildCv.Domain.Readability.ReadabilityReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("ResumeId", "Seq");

                    b.ToTable("Reports", "readability");
                });

            modelBuilder.Entity("BuildCv.Domain.Resumes.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("OwnerId", "Seq")
                        .IsDescending(false, true);

                    b.ToTable("Resumes", "resumes");
                });

            modelBuilder.Entity("BuildCv.Domain.Scoring.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("JobPostingUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ResumeUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ScoredAt");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("ResumeId", "Seq");

                    b.ToTable("Analyses", "scoring");
                });

            modelBuilder.Entity("BuildCv.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("BuildCv.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuildCv.Domain.Jobs.JobPosting", b =>
                {
                    b.OwnsMany("BuildCv.Domain.Jobs.JobRequirement", "Requirements", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("Priority")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Skill")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<double>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.HasIndex("JobPostingId");

                            b1.HasIndex("Skill");

                            b1.ToTable("JobRequirements", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsMany("BuildCv.Domain.Jobs.LanguageRequirement", "LanguageRequirements", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("MinimumLevel")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("JobPostingId");

                            b1.HasIndex("Name");

                            b1.ToTable("LanguageRequirements", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsMany("BuildCv.Domain.Jobs.Responsibility", "Responsibilities", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JobPostingId");

                            b1.ToTable("Responsibilities", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.Navigation("LanguageRequirements");

                    b.Navigation("Requirements");

                    b.Navigation("Responsibilities");
                });

            modelBuilder.Entity("BuildCv.Domain.Organizations.Organization", b =>
                {
                    b.OwnsMany("BuildCv.Domain.Organizations.Membership", "Members", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("Role")
                                .HasColumnType("tinyint");

                            b1.HasKey("Id");

                            b1.HasIndex("OrganizationId", "AccountId")
                                .IsUnique();

                            b1.ToTable("Memberships", "orgs");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("BuildCv.Domain.Readability.ReadabilityReport", b =>
                {
                    b.OwnsOne("BuildCv.Domain.Readability.ReadabilityBreakdown", "Breakdown", b1 =>
                        {
                            b1.Property<Guid>("ReadabilityReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("AchievementsScore")
                                .HasColumnType("float")
                                .HasColumnName("AchievementsScore");

                            b1.Property<double>("AtsParseabilityScore")
                                .HasColumnType("float")
                                .HasColumnName("AtsParseabilityScore");

                            b1.Property<double>("ChronologyScore")
                                .HasColumnType("float")
                                .HasColumnName("ChronologyScore");

                            b1.Property<double>("CompletenessScore")
                                .HasColumnType("float")
                                .HasColumnName("CompletenessScore");

                            b1.Property<double>("ContactScore")
                                .HasColumnType("float")
                                .HasColumnName("ContactScore");

                            b1.Property<string>("Weights")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(false)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("Weights");

                            b1.HasKey("ReadabilityReportId");

                            b1.ToTable("Reports", "readability");

                            b1.WithOwner()
                                .HasForeignKey("ReadabilityReportId");
                        });

                    b.OwnsMany("BuildCv.Domain.Readability.ReadabilityRecommendation", "Recommendations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Impact")
                                .HasColumnType("float");

                            b1.Property<byte>("Kind")
                                .HasColumnType("tinyint");

                            b1.Property<byte[]>("Message")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "ReadabilityRecommendation.Message");

                            b1.Property<byte>("Priority")
                                .HasColumnType("tinyint");

                            b1.Property<Guid>("ReadabilityReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("Section")
                                .HasColumnType("tinyint");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadabilityReportId");

                            b1.HasIndex("Section", "Priority");

                            b1.ToTable("Recommendations", "readability");

                            b1.WithOwner()
                                .HasForeignKey("ReadabilityReportId");
                        });

                    b.Navigation("Breakdown")
                        .IsRequired();

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("BuildCv.Domain.Resumes.Resume", b =>
                {
                    b.OwnsMany("BuildCv.Domain.Resumes.Award", "Awards", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Awarder")
                                .HasMaxLength(768)
                                .HasColumnType("varbinary(768)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Award.Awarder");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("date");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Summary")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Award.Summary");

                            b1.Property<byte[]>("Title")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Award.Title");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Awards", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Certificate", "Certificates", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("CredentialId")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Certificate.CredentialId");

                            b1.Property<byte[]>("CredentialUrl")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Certificate.CredentialUrl");

                            b1.Property<byte[]>("Issuer")
                                .IsRequired()
                                .HasMaxLength(768)
                                .HasColumnType("varbinary(768)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Certificate.Issuer");

                            b1.Property<byte[]>("Name")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Certificate.Name");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ValidityPeriod")
                                .HasMaxLength(21)
                                .IsUnicode(false)
                                .HasColumnType("varchar(21)");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Certificates", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsOne("BuildCv.Domain.Resumes.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Email")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varbinary(512)")
                                .HasColumnName("Contact_Email")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Resume.ContactInformation.Email");

                            b1.Property<byte[]>("FullName")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varbinary(1024)")
                                .HasColumnName("Contact_FullName")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Resume.ContactInformation.FullName");

                            b1.Property<byte[]>("Location")
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Contact_Location")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Resume.ContactInformation.Location");

                            b1.Property<byte[]>("PhoneNumber")
                                .HasMaxLength(128)
                                .HasColumnType("varbinary(128)")
                                .HasColumnName("Contact_PhoneNumber")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Resume.ContactInformation.PhoneNumber");

                            b1.Property<byte[]>("Profiles")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Contact_Profiles")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Resume.ContactInformation.Profiles");

                            b1.Property<byte[]>("Summary")
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Contact_Summary")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Resume.ContactInformation.Summary");

                            b1.Property<byte[]>("Website")
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Contact_Website")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Resume.ContactInformation.Website");

                            b1.HasKey("ResumeId");

                            b1.ToTable("Resumes", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Education", "Educations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Degree")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Education.Degree");

                            b1.Property<byte[]>("FieldOfStudy")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Education.FieldOfStudy");

                            b1.Property<byte[]>("Grade")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Education.Grade");

                            b1.Property<byte[]>("Institution")
                                .IsRequired()
                                .HasMaxLength(768)
                                .HasColumnType("varbinary(768)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Education.Institution");

                            b1.Property<byte?>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasMaxLength(21)
                                .IsUnicode(false)
                                .HasColumnType("varchar(21)");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Educations", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Experience", "Experiences", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Highlights")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Experience.Highlights");

                            b1.Property<byte[]>("Organization")
                                .IsRequired()
                                .HasMaxLength(768)
                                .HasColumnType("varbinary(768)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Experience.Organization");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasMaxLength(21)
                                .IsUnicode(false)
                                .HasColumnType("varchar(21)");

                            b1.Property<byte[]>("Position")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Experience.Position");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Summary")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Experience.Summary");

                            b1.Property<byte>("Type")
                                .HasColumnType("tinyint");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Experiences", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Interest", "Interests", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Keywords")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Interest.Keywords");

                            b1.Property<byte[]>("Name")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Interest.Name");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Interests", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Language", "Languages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Fluency")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Language.Fluency");

                            b1.Property<byte?>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("Name");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Languages", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Project", "Projects", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Description")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Project.Description");

                            b1.Property<byte[]>("Highlights")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Project.Highlights");

                            b1.Property<byte[]>("LiveDemoUrl")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Project.LiveDemoUrl");

                            b1.Property<byte[]>("Name")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Project.Name");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasMaxLength(21)
                                .IsUnicode(false)
                                .HasColumnType("varchar(21)");

                            b1.Property<byte[]>("RepositoryUrl")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Project.RepositoryUrl");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Technologies")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Projects", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Publication", "Publications", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Publisher")
                                .HasMaxLength(768)
                                .HasColumnType("varbinary(768)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Publication.Publisher");

                            b1.Property<DateOnly?>("ReleaseDate")
                                .HasColumnType("date");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Summary")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Publication.Summary");

                            b1.Property<byte[]>("Title")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Publication.Title");

                            b1.Property<byte[]>("Url")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Publication.Url");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Publications", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Reference", "References", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Company")
                                .HasMaxLength(768)
                                .HasColumnType("varbinary(768)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Reference.Company");

                            b1.Property<byte[]>("Email")
                                .HasMaxLength(512)
                                .HasColumnType("varbinary(512)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Reference.Email");

                            b1.Property<byte[]>("Name")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Reference.Name");

                            b1.Property<byte[]>("PhoneNumber")
                                .HasMaxLength(128)
                                .HasColumnType("varbinary(128)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Reference.PhoneNumber");

                            b1.Property<byte[]>("Position")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Reference.Position");

                            b1.Property<byte[]>("ReferenceText")
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Reference.ReferenceText");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("References", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.OwnsMany("BuildCv.Domain.Resumes.Skill", "Skills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Keywords")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<byte?>("Level")
                                .HasColumnType("tinyint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("YearsOfExperience")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("Name");

                            b1.HasIndex("ResumeId");

                            b1.ToTable("Skills", "resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");
                        });

                    b.Navigation("Awards");

                    b.Navigation("Certificates");

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Interests");

                    b.Navigation("Languages");

                    b.Navigation("Projects");

                    b.Navigation("Publications");

                    b.Navigation("References");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("BuildCv.Domain.Scoring.Analysis", b =>
                {
                    b.OwnsMany("BuildCv.Domain.Scoring.Recommendation", "Recommendations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AnalysisId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Impact")
                                .HasColumnType("float");

                            b1.Property<byte>("Kind")
                                .HasColumnType("tinyint");

                            b1.Property<byte[]>("Message")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasAnnotation("BuildCv:Encrypted", true)
                                .HasAnnotation("BuildCv:EncryptionContext", "Recommendation.Message");

                            b1.Property<byte>("Priority")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Section")
                                .HasColumnType("tinyint");

                            b1.HasKey("Id");

                            b1.HasIndex("AnalysisId");

                            b1.HasIndex("Section", "Priority");

                            b1.ToTable("Recommendations", "scoring");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisId");
                        });

                    b.OwnsOne("BuildCv.Domain.Scoring.ScoreBreakdown", "Breakdown", b1 =>
                        {
                            b1.Property<Guid>("AnalysisId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("CertificationsScore")
                                .HasColumnType("float")
                                .HasColumnName("CertificationsScore");

                            b1.Property<double>("EducationScore")
                                .HasColumnType("float")
                                .HasColumnName("EducationScore");

                            b1.Property<double>("ExperienceScore")
                                .HasColumnType("float")
                                .HasColumnName("ExperienceScore");

                            b1.Property<double>("LanguagesScore")
                                .HasColumnType("float")
                                .HasColumnName("LanguagesScore");

                            b1.Property<double>("ProjectsScore")
                                .HasColumnType("float")
                                .HasColumnName("ProjectsScore");

                            b1.Property<double>("SkillsScore")
                                .HasColumnType("float")
                                .HasColumnName("SkillsScore");

                            b1.Property<string>("Weights")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(false)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("Weights");

                            b1.HasKey("AnalysisId");

                            b1.ToTable("Analyses", "scoring");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisId");
                        });

                    b.Navigation("Breakdown")
                        .IsRequired();

                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
